#Bambu engine configuration file
#do not edit this file!
#bu dosyayı düzenleme!

import os
import pygame

pygame_version = pygame.__version__
engine_version = "3.5"

normal_title = "Bambu Engine"
#engine_icon = os.getcwd() + "\icon.png"
welcome = f"""
Bambu Engine {engine_version}
"""
