#Bambu engine configuration file
#do not edit this file!
#bu dosyayı düzenleme!

import os
import pygame

pygame_version = pygame.__version__
engine_version = 3.4.1

normal_title = "Bambu Engine"
engine_icon = os.getcwd() + "\icon.png"
welcome = """
Bambu Engine 3.4.1 (Test Sürümü)
"""
